name: CI

on:
  pull_request:

jobs:
  linux-64:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run setup script
        run: |
          sed -i "s/master/${GITHUB_MASTER}/g" bash/pixi/install.sh
          sed -i "s/master/${GITHUB_MASTER}/g" bash/pixi/pixi_setup.sh
          bash/pixi/pixi_setup.sh

  osx-64:
    runs-on: macos-13
    strategy:
      fail-fast: false

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run setup script
        run: |
          sed -i "s/master/${GITHUB_MASTER}/g" bash/pixi/install.sh
          sed -i "s/master/${GITHUB_MASTER}/g" bash/pixi/pixi_setup.sh
          bash/pixi/pixi_setup.sh

  osx-arm64:
    runs-on: macos-14
    strategy:
      fail-fast: false

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run setup script
        run: |
          sed -i "s/master/${GITHUB_MASTER}/g" bash/pixi/install.sh
          sed -i "s/master/${GITHUB_MASTER}/g" bash/pixi/pixi_setup.sh
          bash/pixi/pixi_setup.sh
